### ISSUE TITLE
Sync Unit tests do not pass. 

### ISSUE THREAD

**Issue by gnuton** [faisalraja/flickrsmartsync#53]
gnuton@david:~/GIT/FLICKRSMARTSYNC/flickrsmartsync/test$ sudo ./test_sync.py 
test_download (**main**.syncTest) ... ERROR
test_sync (**main**.syncTest) ... ERROR
test_upload (**main**.syncTest) ... ERROR
# 
## ERROR: test_download (**main**.syncTest)

Traceback (most recent call last):
  File "./test_sync.py", line 55, in setUp
    self.sync = Sync(args(), self.local, self.remote)
  File "/home/gnuton/GIT/FLICKRSMARTSYNC/flickrsmartsync/test/../flickrsmartsync/sync.py", line 19, in **init**
    if self.cmd_args.ignore_ext:
AttributeError: args instance has no attribute 'ignore_ext'
# 
## ERROR: test_sync (**main**.syncTest)

Traceback (most recent call last):
  File "./test_sync.py", line 55, in setUp
    self.sync = Sync(args(), self.local, self.remote)
  File "/home/gnuton/GIT/FLICKRSMARTSYNC/flickrsmartsync/test/../flickrsmartsync/sync.py", line 19, in **init**
    if self.cmd_args.ignore_ext:
AttributeError: args instance has no attribute 'ignore_ext'
# 
## ERROR: test_upload (**main**.syncTest)

Traceback (most recent call last):
  File "./test_sync.py", line 55, in setUp
    self.sync = Sync(args(), self.local, self.remote)
  File "/home/gnuton/GIT/FLICKRSMARTSYNC/flickrsmartsync/test/../flickrsmartsync/sync.py", line 19, in **init**
    if self.cmd_args.ignore_ext:
AttributeError: args instance has no attribute 'ignore_ext'

---

Ran 3 tests in 0.001s

FAILED (errors=3)

**Comment by gnuton** [comment]
Pull request sent to fix this issue.
