### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by artemklevtsov** [faisalraja/flickrsmartsync#59]
Hi.

After certain update flickrsmartsync stopped working.

```python
Traceback (most recent call last):
  File "/usr/bin/flickrsmartsync", line 9, in <module>
    load_entry_point('flickrsmartsync==0.2.1.post0', 'console_scripts', 'flickrsmartsync')()
  File "/usr/lib/python2.7/site-packages/flickrsmartsync/__init__.py", line 71, in main
    remote = Remote(args)
  File "/usr/lib/python2.7/site-packages/flickrsmartsync/remote.py", line 24, in __init__
    token = self.auth_api()
  File "/usr/lib/python2.7/site-packages/flickrsmartsync/remote.py", line 37, in auth_api
    (token, frob) = self.api.get_token_part_one(perms='delete')
  File "/usr/lib/python2.7/site-packages/flickrapi/__init__.py", line 759, in get_token_part_one
    rsp = self.auth_getFrob(auth_token=None, format='xmlnode')
  File "/usr/lib/python2.7/site-packages/flickrapi/__init__.py", line 357, in handler
    parse_format=args['format'], **args)
  File "/usr/lib/python2.7/site-packages/flickrapi/__init__.py", line 436, in __wrap_in_parser
    data = wrapped_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flickrapi/__init__.py", line 410, in __flickr_call
    flicksocket = urllib2.urlopen(url, post_data)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

I use Arch Linux and this package: https://aur.archlinux.org/packages/python2-flickrsmartsync-git/

**Comment by artemklevtsov** [comment]
I'm so sorry. Seems problem in my internet provider.
