### ISSUE TITLE
Not able to authorize the app

### ISSUE THREAD

**Issue by florentvaldelievre** [faisalraja/flickrsmartsync#69]
python flickrsmartsync
Please authorized this app then hit enter:
ERROR:flickrsmartsync:Please authorized to use

A web browser is opening on flickr.com but not asking for authorization.

Is the app still working ?

Thanks

**Comment by fret2buzz** [comment]
The same issue for me. Auth link redirects to homepage hence I'm unable to authorize the app.

**Comment by inspector2211** [comment]
I had the same issue.  I created a new repository 'flickrsmartsync_oauth' which supports oauth using the latest version (version 2.3) of 'flickrapi'.

You can try:

1. Download flickrsmartsync_oauth
    git clone https://github.com/inspector2211/flickrsmartsync_oauth

2. Create your own personal Flickr API keys
    https://www.flickr.com/services/apps/create/apply

3. Add api_key and api_secret to flickrsmartsync_oauth/flickrsmartsync_oauth/config.py, as follows:
    api_key = u'<API_KEY>'
    api_secret = u'<API_SECRET>'

4. Run the install script
    python setup.py install

5. Everything else should be the same as flickrsmartsync

6. Examining the code, I noticed that the command-line monitoring daemon may run only after an upload (not a download or sync) and I think this may be a problem with indentation in the code.  See 'sync.py', line 38.

In my opinion, flickrsmartsync is much better than competing commercial products like ZillaUploader and I hope that the owner will continue to maintain it.

**Comment by zdmytriv** [comment]
Same error.

**Comment by zdmytriv** [comment]
@inspector2211 

I've tried with `flickrsmartsync_oauth` and got an error
```
$ flickrsmartsync_oauth
Traceback (most recent call last):
  File "/usr/local/bin/flickrsmartsync_oauth", line 11, in <module>
    load_entry_point('flickrsmartsync-oauth==0.1.0.post0', 'console_scripts', 'flickrsmartsync_oauth')()
  File "/usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg/flickrsmartsync_oauth/__init__.py", line 57, in main
    remote = Remote(args)
  File "/usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg/flickrsmartsync_oauth/remote.py", line 21, in __init__
    self.auth_api() # removed return token
  File "/usr/local/lib/python2.7/site-packages/flickrsmartsync_oauth-0.1.0.post0-py2.7.egg/flickrsmartsync_oauth/remote.py", line 38, in auth_api
    if not self.api.token_valid(perms=u'delete'):
  File "/usr/local/lib/python2.7/site-packages/flickrapi/__init__.py", line 357, in handler
    parse_format=args['format'], **args)
  File "/usr/local/lib/python2.7/site-packages/flickrapi/__init__.py", line 444, in __wrap_in_parser
    return parser(self, data)
  File "/usr/local/lib/python2.7/site-packages/flickrapi/__init__.py", line 285, in parse_etree
    raise FlickrError(u'Error: %(code)s: %(msg)s' % err.attrib)
flickrapi.exceptions.FlickrError: Error: 112: Method "flickr.token.valid" not found
```

**Comment by inspector2211** [comment]
@zdmytriv 

Not sure what is happening here.  'Method "flickr.token.valid" not found' is an error being generated by flickrapi.  There may be a conflict with flickr tokens between the old authentication method and _oauth.

I removed old flickrsmartsync tokens before running flickrsmartsync_oauth.  You can check for a .flickr file or directory in your home directory, rename it and try again.  Good luck.

**Comment by inspector2211** [comment]
@zdmytriv 

I think you are using version 1.4.4 of flickrapi (that is, the version included with flickrsmartsync).

The last three lines of your error refer to line 285 of flickrapi/__init__.py
    raise FlickrError(u'Error: %(code)s: %(msg)s' % err.attrib).

flickrsmartsync_oauth uses the latest version 2.3 of flickrapi.  In version 2.3, flickrapi/__init__.py is only 81 lines.

Please let us know if it works.  Any other questions regarding flickrsmartsync_oauth can be sent to that page, rather than flickrsmartsync.

**Comment by zdmytriv** [comment]
I've tried from clean virtual env and worked just fine. Thanks all for help.

**Comment by titimoi** [comment]
@inspector2211 I run flickrsmartsync_oauth on a server without browser, so I can't pass the Authentication part :
` flickrsmartsync_oauth
Authenticating
ERROR:flickrsmartsync_oauth:Authentication is required.
`
It seems that my problem comes form the method I'd like to get the url instead of calling the method 
` self.api.authenticate_via_browser(perms=u'delete')` 

Could you guide me on what to do to get the url to call in my browser ?

**Comment by inspector2211** [comment]
@titimoi

Underneath the call for *self.api.authenticate_via_browser* in *remote.py*
is a multi-line comment which breaks the authentication process into
discrete steps.  I have not tested this code (sourced from *flickrapi*
documentation) but you can see that the authentication URL is received from
the *self.api.auth_url* method before being passed to the web browser.

Good luck.

        # Authentication

        if not self.api.token_valid(perms=u'delete'):

            print('Authenticating...')

        try:

            self.api.authenticate_via_browser(perms=u'delete')

            """

            # Get a request token

            # self.api.get_request_token(oauth_callback='oob')

            self.api.get_request_token()


            # Open a browser at the authentication URL.

            authorize_url = self.api.auth_url(perms=u'delete')

            webbrowser.open_new_tab(authorize_url)


            # Get the verifier code from the user.

            verifier = str(input('Please enter verfication code: '))


            # Trade the request token for an access token

            # added unicode()

            self.api.get_access_token(unicode(verifier))

            """

        except:

            logger.error('Authentication is required.')

            exit(0)

**Comment by titimoi** [comment]
Thanks a lot for your help @inspector2211 I managed to get it working. I had too specify the callback=oob (I used the code of this fork https://github.com/danielhoherd/flickrsmartsync/commit/70efead5debe6995e040f57cf391e34895bd5442)

I am syncing about 250 folders, but most of the time, it can't run fully because I get a "Connection aborted" : 
```

Traceback (most recent call last):
  File "/usr/local/bin/flickrsmartsync_oauth", line 9, in <module>
    load_entry_point('flickrsmartsync-oauth==0.1.0-r0', 'console_scripts', 'flickrsmartsync_oauth')()
  File "/usr/local/lib/python2.7/dist-packages/flickrsmartsync_oauth-0.1.0_r0-py2.7.egg/flickrsmartsync_oauth/__init__.py", line 59, in main
    sync.start_sync()
  File "/usr/local/lib/python2.7/dist-packages/flickrsmartsync_oauth-0.1.0_r0-py2.7.egg/flickrsmartsync_oauth/sync.py", line 35, in start_sync
    self.upload()
  File "/usr/local/lib/python2.7/dist-packages/flickrsmartsync_oauth-0.1.0_r0-py2.7.egg/flickrsmartsync_oauth/sync.py", line 149, in upload
    photos = self.remote.get_photos_in_set(folder)
  File "/usr/local/lib/python2.7/dist-packages/flickrsmartsync_oauth-0.1.0_r0-py2.7.egg/flickrsmartsync_oauth/remote.py", line 148, in get_photos_in_set
    photos_in_set = json.loads(self.api.photosets_getPhotos(**photoset_args))
  File "build/bdist.linux-armv7l/egg/flickrapi/call_builder.py", line 38, in __call__
  File "build/bdist.linux-armv7l/egg/flickrapi/core.py", line 337, in do_flickr_call
  File "build/bdist.linux-armv7l/egg/flickrapi/core.py", line 399, in _wrap_in_parser
  File "build/bdist.linux-armv7l/egg/flickrapi/core.py", line 377, in _flickr_call
  File "build/bdist.linux-armv7l/egg/flickrapi/auth.py", line 256, in do_request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Have you guys experienced this too ?

**Comment by inspector2211** [comment]
@titimoi I have seen no connection problems.

**Comment by gitothy** [comment]
Sorry appreciate this isn't a free help forum, but I've followed the instructions and seeing the following error when running:
```
tim@readynas:/photos$ flickrsmartsync_oauth
Traceback (most recent call last):
  File "/usr/local/bin/flickrsmartsync_oauth", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: flickrapi
tim@readynas:/photos$
```

**Seems like a total fail to run at all??**

Full disclosure:
- I used to have flickrsmartsync installed
- I originally installed without having the config.py present. Then realised after and have re-installed over the top with this file present.
